apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airweave-svc.fullname" . }}
  labels:
    {{- include "airweave-svc.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  {{- range $key, $value := .Values.env }}
  {{- if and (ne $key "additional") (kindIs "string" $value) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
