{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "airweave-svc.fullname" . }}
  labels:
    {{- include "airweave-svc.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: ClusterSecretStore

  target:
    name: {{ include "airweave-svc.fullname" . }}
    creationPolicy: Owner
    deletionPolicy: Retain

  {{- if and (.Values.externalSecrets.refreshInterval) (ne (.Values.externalSecrets.refreshInterval | int) 0) }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  {{- end }}

  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.secretName }}
        {{- if .Values.externalSecrets.secretVersion }}
        version: {{ .Values.externalSecrets.secretVersion }}
        {{- end }}
{{- end }}
